### ISSUE TITLE
Issue #1: Update readme with install/workflow instructions

### ISSUE THREAD

**Issue by kristentortorelli** [AvraSaslow/ea-rimorphis#2]
@AvraSaslow Please update readme with complete install/workflow running instructions. Can use https://github.com/earthlab/earthpy readme file as a guide.

**Comment by AvraSaslow** [comment]
Resolved

**Comment by AvraSaslow** [comment]
@eculler Just wanted to follow up - we've added some detail in our instructions for running the code.
